version: '3'
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: pushbot
      POSTGRES_PASSWORD: shhh
    ports:
    - '5432:5432'
  pushbot:
    build: .
    volumes:
    - ".:/usr/src/app/"
    environment:
      DATABASE_URL: postgres://pushbot:shhh@postgres/pushbot
      HUBOT_SLACK_TOKEN:
      SLACK_CLIENT_ID:
      SLACK_CLIENT_SECRET:
      SLACK_TEAM_ID:
      SESSION_SECRET:
      DEV_USERNAME:
      HUBOT_MARKOV_STORAGE: postgres
      HUBOT_MARKOV_STORAGE_URL: postgres://pushbot:shhh@postgres/pushbot
      HUBOT_MARKOV_LEARN_MIN:
      HUBOT_MARKOV_GENERATE_MAX:
      HUBOT_AUTH_ADMIN:
      HUBOT_WEATHER_APIKEY:
      API_BASE_URL: http://localhost:8080
      WEB_BASE_URL:
    ports:
    - '8080:8080'
    depends_on:
    - postgres
